Resources:
  AssetsMetaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.stage}-assets-meta-2
      AttributeDefinitions:
      - AttributeName: fileType
        AttributeType: S
      - AttributeName: fileName
        AttributeType: S
      KeySchema:
      - AttributeName: fileType
        KeyType: HASH
      - AttributeName: fileName
        KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  WikiArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.stage}-wiki-articles
      AttributeDefinitions:
      - AttributeName: articleLocale
        AttributeType: S
      - AttributeName: articleID
        AttributeType: S
      KeySchema:
      - AttributeName: articleLocale
        KeyType: HASH
      - AttributeName: articleID
        KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
