Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # CORS configuration
      CorsConfiguration:
        CorsRules:
        -
          AllowedOrigins:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - POST
          - DELETE
          - HEAD
          AllowedHeaders:
          - '*'
          ExposedHeaders:
          - ETag
          MaxAge: 3000

Outputs:
  AttachmentsBucketName:
    Value:
      Ref: AssetsBucket
