  create:
    handler: handlers/create.main
    events:
    - http:
        path: assets
        method: post
        cors: true
        authorizer: aws_iam
  get:
    handler: handlers/get.main
    events:
    - http:
        path: assets/{fileName}
        method: get
        cors: true
        authorizer: aws_iam
  list:
    handler: handlers/list.main
    events:
    - http:
        path: assets/list/{fileType}
        method: get
        cors: true
        authorizer: aws_iam
  update:
    handler: handlers/update.main
    events:
    - http:
        path: assets/{fileName}
        method: put
        cors: true
        authorizer: aws_iam
  delete:
    handler: handlers/delete.main
    events:
    - http:
        path: assets/{fileName}
        method: delete
        cors: true
        authorizer: aws_iam
  resize:
    handler: handlers/resize.main
    events:
    - http:
        path: assets/resize/{fileName}
        method: put
        cors: true
        authorizer: aws_iam
    memorySize: 1024
    timeout: 15